Error: Replace ok_or_else() with with_context()
Keep error generation style same. And anyhow! is not
required when using with_context.

Signed-off-by: Keqian Zhu <zhukeqian1@huawei.com>