fix mod test unresolved import error
mod test error: unresolved import `virtio::VIRTIO_GPU_FORMAT_INVALID_UNORM`
Fixes: 721a74a3d68d ("vitio: Remove redundant pub declarations")

Signed-off-by: yezengruan <yezengruan@huawei.com>